### ISSUE TITLE
Create settings page

### ISSUE THREAD

**Issue by roji-tech** [tbf-challenge/teamwork-fe#36]

**Comment by TonniPaul** [comment]
Are we to come up with our own concepts?? or there is a pre-existing design to work with??

**Comment by jakazzy** [comment]
@TonniPaul There are pre-existing designs to work with
https://www.figma.com/file/gU3GHIN3tuqKqPFfGvVaez/GITHUB?node-id=117%3A35

**Comment by TonniPaul** [comment]
Thanks
